source 'https://rubygems.org'

language: ruby
cache: bundler
sudo: required

addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable

before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
script: bundle exec cucumber

branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com



