sudo: required
language: ruby
cache: bundler


rvm: 2.2

before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
script: bundle exec cucumber

branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com

