sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - gem install rake
  - gem install watir
  - gem install colorize
  - bundle install
  
language: ruby

notifications:
  email:
      - iamsmj@gmail.com