language : ruby
sudo: required
language: ruby

before install:
  - gem install bundle
  - gem install cucumber
  - gem install ruby
  - gem install watir
  - gem install rake

env: TARGET_LANG=ruby

email notifications: false

