sudo: required
language: ruby
cache: bundler


rvm: 2.2

before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
        - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
          - unzip chromedriver_linux64.zip
          - sudo chmod u+x chromedriver
          - sudo mv chromedriver /usr/bin/
          - export CHROME_BIN=chromium-browser
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - sleep 3
          - ./travis_before_install

script: bundle exec cucumber

branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com

